// VI Complete Product Catalog — 11 Ayurvedic Formulas
export const ALL_PRODUCTS = [
  {
    id:1, icon:'💊', color:'#7C3AED',
    brand:'Vajra Veerya', hindi:'वज्र वीर्य', cat:'Testosterone Boost',
    tagline:'The Testosterone Rebuilder',
    mrp:1199, price:849, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Morning · After Breakfast', timingIcon:'🌅',
    benefits:['Testosterone Rise','Energy Surge','Muscle Strength'],
    detailedBenefits:['Boosts free testosterone by up to 40%','Increases morning vitality','Supports lean muscle','Improves stamina'],
    ingredients:'Ashwagandha KSM-66 (500mg), Shilajit Resin (300mg), Safed Musli (200mg), Gokshura (200mg), Kapikacchu (150mg)',
    usage:'2 capsules daily after breakfast with warm milk',
    scienceNote:'Ashwagandha KSM-66 is clinically proven to increase testosterone by 17% in 8 weeks.',
    rating:4.9, reviews:3241,
  },
  {
    id:2, icon:'⏱️', color:'#D97706',
    brand:'Sthambhan Shakti', hindi:'स्थम्भन शक्ति', cat:'Timing Control',
    tagline:'The Control Formula',
    mrp:999, price:699, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Pre-Activity (1 hr before)', timingIcon:'⚡',
    benefits:['Better Control','Longer Duration','Confidence'],
    detailedBenefits:['Extends duration via neuromuscular support','Reduces anxiety-triggered early finish','Builds long-term timing control','Increases confidence'],
    ingredients:'Jaiphal (200mg), Akarkara (150mg), Vidari Kanda (200mg), Ashwagandha (300mg), Shatavari (200mg)',
    usage:'2 capsules 1 hour before activity, or daily for long-term results',
    scienceNote:'Akarkara (Pellitory) is a natural neurological tonic used since 1000 BCE for stamina control.',
    rating:4.8, reviews:2847,
  },
  {
    id:3, icon:'🔥', color:'#DC2626',
    brand:'Dridha Stambh', hindi:'दृढ स्तम्भ', cat:'Erection Support',
    tagline:'The Vascular Strength Formula',
    mrp:1099, price:779, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Night · After Dinner', timingIcon:'🌙',
    benefits:['Stronger Erection','Blood Flow','Vascular Health'],
    detailedBenefits:['Increases nitric oxide for better blood flow','Strengthens vascular tone','Improves firmness and duration','Supports long-term health'],
    ingredients:'Vidarikanda (300mg), Kaunch Beej (200mg), Gokshura (200mg), Swarna Bhasma (50mg), Shilajit (200mg)',
    usage:'2 capsules after dinner with warm milk',
    scienceNote:'Gokshura increases luteinizing hormone directly stimulating testosterone and improving vascular response.',
    rating:4.8, reviews:2103,
  },
  {
    id:4, icon:'🧠', color:'#0891B2',
    brand:'Manas Veerya', hindi:'मनस् वीर्य', cat:'Stress & Calm',
    tagline:'The Cortisol Crusher',
    mrp:899, price:649, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Morning & Night', timingIcon:'🌓',
    benefits:['Calm Mind','Cortisol Control','Focus & Sleep'],
    detailedBenefits:['Reduces cortisol (the testosterone killer)','Calms nervous system','Improves deep sleep quality','Enhances mental clarity'],
    ingredients:'Brahmi (300mg), Ashwagandha (400mg), Jatamansi (200mg), L-Theanine (200mg), Magnesium Glycinate (150mg)',
    usage:'1 capsule morning + 1 capsule before bed',
    scienceNote:'Brahmi reduces cortisol by 28% in clinical studies — cortisol directly suppresses testosterone.',
    rating:4.8, reviews:1654,
  },
  {
    id:5, icon:'⚡', color:'#CA8A04',
    brand:'Kaam Agni Ras', hindi:'काम अग्नि रस', cat:'Pre-Intimacy Shots',
    tagline:'The Ignition Shot',
    mrp:1499, price:999, form:'Liquid Shots · 30ml each', duration:'30-shot pack',
    timing:'Pre-Activity (30-45 mins)', timingIcon:'🎯',
    benefits:['Instant Ignition','Fast Absorb','Passion Boost'],
    detailedBenefits:['Works in 30 minutes — fast liquid absorption','Ignites desire and mental readiness','Boosts confidence before intimacy','Saffron+Shilajit synergy'],
    ingredients:'Saffron Extract (50mg), Shilajit Resin (200mg), Zinc Bisglycinate (15mg), Panax Ginseng (200mg), Vitamin B12 (500mcg), Manuka Honey Base',
    usage:'1 shot 30–45 minutes before activity. Shake well before drinking.',
    scienceNote:'Saffron has 9 clinical trials supporting its role in improving sexual desire and performance.',
    rating:4.9, reviews:3102,
  },
  {
    id:6, icon:'🌿', color:'#15803D',
    brand:'Rasayana Shakti', hindi:'रसायन शक्ति', cat:'Night Recovery',
    tagline:'The Sleep & Rebuild Formula',
    mrp:1099, price:799, form:'Powder · 300g tub', duration:'30-day supply',
    timing:'Night · Before Sleep (30 mins)', timingIcon:'🌙',
    benefits:['Deep Sleep','Hormone Repair','Morning Energy'],
    detailedBenefits:['Enters deep sleep faster','Repairs hormones during sleep','Wake up energised','Reduces morning grogginess'],
    ingredients:'Magnesium Glycinate (400mg), Tart Cherry (500mg), L-Glycine (3000mg), Zinc Citrate (15mg), Ashwagandha (300mg), Melatonin (0.5mg)',
    usage:'1 scoop (10g) in 150ml warm water, 30 minutes before bed',
    scienceNote:'Testosterone is 70% produced during deep sleep. This formula extends deep sleep by up to 90 minutes.',
    rating:4.7, reviews:1287,
  },
  {
    id:7, icon:'🛢️', color:'#92400E',
    brand:'Vajra Tailam', hindi:'वज्र तैलम्', cat:'Performance Oil',
    tagline:'The Ancient Performance Oil',
    mrp:799, price:549, form:'Oil · 30ml bottle', duration:'60-day supply',
    timing:'Pre-Activity (15 mins before)', timingIcon:'🎯',
    benefits:['Fast Absorption','Blood Flow','Enhanced Sensitivity'],
    detailedBenefits:['Increases local blood flow within 15 minutes','Enhances nerve sensitivity','Stronger sustained performance','Ancient Siddha formula — pure'],
    ingredients:'Nirgundi Cold-Press Oil (base), Akarkara Extract, Clove Essential Oil, White Sesame Oil, Camphor (trace)',
    usage:'Apply 5–8 drops gently. Massage for 5 minutes. Wait 15 minutes before activity.',
    scienceNote:'Akarkara increases acetylcholine — the nerve signal for sensation. Used in Siddha medicine 2,000+ years.',
    rating:4.7, reviews:1923,
  },
  {
    id:8, icon:'💪', color:'#1E3A5F',
    brand:'Yuva Vajra', hindi:'युवा वज्र', cat:'35+ Performance',
    tagline:'The Age Reversal Stack',
    mrp:1299, price:949, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Morning · With Warm Milk', timingIcon:'🌅',
    benefits:['Age Reversal','Testosterone Restore','Energy & Drive'],
    detailedBenefits:['Counteracts 3–5% annual testosterone decline','Restores energy to decade-younger levels','Improves recovery time','Supports bone density'],
    ingredients:'Shilajit Resin (500mg), Safed Musli (300mg), Ashwagandha KSM-66 (400mg), Shatavari (200mg), Swarna Makshik Bhasma (100mg)',
    usage:'2 capsules every morning with warm milk',
    scienceNote:'Shilajit Resin + Ashwagandha KSM-66: most studied Ayurvedic stack for age-related testosterone decline.',
    rating:4.9, reviews:2567,
  },
  {
    id:9, icon:'❤️', color:'#BE185D',
    brand:'Kaam Veerya', hindi:'काम वीर्य', cat:'Libido Boost',
    tagline:'The Desire Reigniter',
    mrp:999, price:729, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Night · After Dinner', timingIcon:'🌙',
    benefits:['Reignite Desire','Hormonal Balance','Vitality'],
    detailedBenefits:['Reignites libido within 2 weeks','Balances LH and FSH hormones','Increases spontaneous arousal','Rebuilds emotional connection'],
    ingredients:'Kapikacchu (300mg), Shatavari (200mg), Gokshura (200mg), Safed Musli (200mg), Ras Sindoor (50mg), Clove Extract (100mg)',
    usage:'2 capsules after dinner daily',
    scienceNote:'Kapikacchu contains L-DOPA — precursor to dopamine, directly linked to sexual desire and motivation.',
    rating:4.8, reviews:2198,
  },
  {
    id:10, icon:'🧬', color:'#0D9488',
    brand:'Beej Shakti', hindi:'बीज शक्ति', cat:'Reproductive Vitality',
    tagline:'The Fertility Support Stack',
    mrp:1199, price:849, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Morning · After Breakfast', timingIcon:'🌅',
    benefits:['Reproductive Vitality','Hormonal Support','Quality'],
    detailedBenefits:['Improves reproductive health markers','Supports hormonal balance','Increases zinc and selenium levels','Traditional Ayurvedic tonic'],
    ingredients:'Ashwagandha (300mg), Shatavari (200mg), Kapikacchu (200mg), Zinc Citrate (20mg), Selenium (60mcg), Gokshura (200mg), Vidarikanda (200mg)',
    usage:'2 capsules daily after breakfast',
    scienceNote:'Ashwagandha + Zinc improves key reproductive health markers by up to 53% in 3 months.',
    rating:4.7, reviews:1432,
  },
  {
    id:11, icon:'👑', color:'#B8811A',
    brand:'Maha Vajra', hindi:'महावज्र', cat:'Ultra Performance',
    tagline:'The Complete VI Protocol',
    mrp:1999, price:1499, form:'Capsules · 60 count', duration:'30-day supply',
    timing:'Morning & Night', timingIcon:'🌓',
    benefits:['Maximum Potency','All-in-One Power','Premium Results'],
    detailedBenefits:['Highest-grade formula in VI range','Combines 7 premium ingredients','For men who want the best','Swarna Bhasma — 24K gold Ayurvedic'],
    ingredients:'Shilajit Resin (500mg), Swarna Bhasma (100mg), Ashwagandha KSM-66 (400mg), Safed Musli (300mg), Gokshura (200mg), Kapikacchu (200mg), Saffron (50mg)',
    usage:'1 capsule morning + 1 capsule night with warm milk',
    scienceNote:'Swarna Bhasma (gold ash) prescribed in Ayurveda for 3,000+ years as the ultimate male vitality rejuvenator.',
    rating:5.0, reviews:987,
  },
]
export const getProductById = (id) => ALL_PRODUCTS.find(p => p.id === id)
